// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFMdqyjZwhVrq5JcD2etNXs6xvG3q-UIQ',
    appId: '1:236757949816:web:08af03e80e94fa6d923c8d',
    messagingSenderId: '236757949816',
    projectId: 'spiceway-8848e',
    authDomain: 'spiceway-8848e.firebaseapp.com',
    storageBucket: 'spiceway-8848e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zWZKLYnevovJy5n8ihzI8-6DDgdKtFA',
    appId: '1:236757949816:android:7592cfcf45c698cf923c8d',
    messagingSenderId: '236757949816',
    projectId: 'spiceway-8848e',
    storageBucket: 'spiceway-8848e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjSCU4eZi6AGHwShtCSjrjJ3aESqLTNQs',
    appId: '1:236757949816:ios:13e26d2463f2afa6923c8d',
    messagingSenderId: '236757949816',
    projectId: 'spiceway-8848e',
    storageBucket: 'spiceway-8848e.appspot.com',
    iosClientId: '236757949816-lvmorrupl0m1ptrdvrh9uhptfaeril0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.spiceway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjSCU4eZi6AGHwShtCSjrjJ3aESqLTNQs',
    appId: '1:236757949816:ios:13e26d2463f2afa6923c8d',
    messagingSenderId: '236757949816',
    projectId: 'spiceway-8848e',
    storageBucket: 'spiceway-8848e.appspot.com',
    iosClientId: '236757949816-lvmorrupl0m1ptrdvrh9uhptfaeril0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.spiceway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFMdqyjZwhVrq5JcD2etNXs6xvG3q-UIQ',
    appId: '1:236757949816:web:7aadc457c1652a20923c8d',
    messagingSenderId: '236757949816',
    projectId: 'spiceway-8848e',
    authDomain: 'spiceway-8848e.firebaseapp.com',
    storageBucket: 'spiceway-8848e.appspot.com',
  );
}
